name: semistandard
run-name: Semi-Standard Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn install
      - name: Semi-Standard test
        run: yarn test
      
